import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme";
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const robotMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DayApp App",
  description: "Generated by Sukhraj next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${robotMono.variable} ${robotMono.variable} antialiased`}>
          <ThemeProvider theme={theme}>
              {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
